export const GfxLandscape = {
  EditName: 'string',
  EditGroups: 'string[]',
  LogicType: 'number',
  LogicMaximumValency: 'number',
  LogicIsWorkable: 'boolean',
  logicispileableonmap: 'boolean',
  LogicWalkBlockArea: 'number[][]',
  LogicBuildBlockArea: 'number[][]',
  LogicWorkArea: 'number[][]',
  GfxBobLibs: 'string[]',
  GfxPalette: 'string[]',
  GfxFrames: '[number, number[]]',
  GfxStatic: 'boolean',
  GfxLoopAnimation: 'boolean',
  GfxShadingFactor: 'number',
  GfxUserFXMatrix: 'number',
  GfxDynamicBackground: 'boolean',
  gfxdrawvoidever: 'boolean',
  GfxTransition: '[number,string]',
}